### ISSUE TITLE
tox?

### ISSUE THREAD

**Issue by IuryAlves** [jcemelanda/DMTools#2]
Podemos usar tox para rodar os testes ?

**Comment by jcemelanda** [comment]
Não usei esse tox ainda, mas pode ser, vc tem usado ele?
Em 07/07/2016 22:47, "iury" notifications@github.com escreveu:

**Comment by IuryAlves** [comment]
@jcemelanda O tox é uma ferramenta de automatização, ele cria o virtualenv, roda testes unitários e etc. Ele também permite rodar os testes em várias versões do python.

**Comment by jcemelanda** [comment]
Gostei
Em 09/07/2016 12:59, "iury" notifications@github.com escreveu:

**Comment by CEDSO** [comment]
Blz

**Comment by IuryAlves** [comment]
resolvido pela 2720595c4b311b5042217897fb4e57023dc3fa95
